INSERT IGNORE INTO locations (location_name, city) VALUES
('Gulshan', 'Dhaka'),
('Banani', 'Dhaka'),
('Dhanmondi', 'Dhaka'),
('Motijheel', 'Dhaka'),
('Uttara', 'Dhaka'),
('Cox''s Bazar Sea Beach', 'Cox''s Bazar'),
('Inani Beach', 'Cox''s Bazar'),
('Sylhet Tea Capital', 'Sylhet'),
('Ratargul Swamp Forest', 'Sylhet'),
('Chittagong Port City', 'Chittagong'),
('Rangamati Hill District', 'Chittagong'),
('Rajshahi Silk City', 'Rajshahi'),
('Puthia Temple Complex', 'Rajshahi'),
('Khulna Mangrove Gateway', 'Khulna'),
('Sundarbans Gateway', 'Khulna'),
('Barishal River Port', 'Barishal'),
('Rangpur Green Valley', 'Rangpur'),
('Mymensingh Agricultural Hub', 'Mymensingh'),
('Comilla Ancient City', 'Comilla'),
('Bandarban Hill Tracts', 'Chittagong');
